name: Build and Release Workflow

on:
  push:
    branches: '*'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches: '*'

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
            distribution: 'temurin'
            java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Run Flutter test
        run: flutter test

      - name: Build android apk
        run: flutter build apk --split-per-abi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk-${{ github.run_id }}.zip
          path: build/app/outputs/apk/release/*.apk

  release:
    needs: test-and-build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Get version from tag
        id: get-version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Download artifact from test job
        id: donwload-artifact
        uses: actions/download-artifact@v4
        with:
          name: apk-${{ github.run_id }}.zip

      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v2

      - name: Rename release assets
        run: |
            echo ${{ steps.donwload-artifact.outputs.download-path }}
            echo ${{ github.repository.name }}
            echo ${{ steps.get-version.outputs.VERSION }}
            for ARCH in armeabi-v7a arm64-v8a x86_64; do
                mv "${{ steps.donwload-artifact.outputs.download-path }}/app-${ARCH}-release.apk" \
                "${{ github.repository.name }}-${{ steps.get-version.outputs.VERSION }}-${ARCH}.apk"
            done

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: ${{ steps.extract-release-notes.outputs.release_notes }}
          files: ${{ steps.donwload-artifact.outputs.download-path }}/*.apk